server:
  address: 0.0.0.0
  port: ${PORT:8083}

spring:
  application:
    name: INTERVIEW-SERVICE

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

groq:
  api:
    key: ${GROQ_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO